"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
console.log("Addition Operation");
console.log(3 + 5);
console.log("Subtraction Operation");
console.log(12 - 4);
console.log("Multiplication Operation");
console.log(2 * 4);
console.log("Division Operation");
console.log(16 / 2);
