"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
console.log("\nCondition with Strings\n");
var name = "Salman";
console.log(name === "salman");
console.log(name === "Salman");
console.log(name.toLowerCase() === "salman");
console.log(name.toLowerCase() === "SALMAN");
console.log("\nCondition with Number\n");
var age = 22;
console.log(age === 21);
console.log(age === 22);
console.log(age > 20);
console.log(age < 20);
console.log(age >= 22);
console.log(age <= 20);
console.log("\nCondition using 'OR' and 'AND'\n");
console.log(age >= 22 && name === "Salman");
console.log(age >= 22 && name === "salman");
console.log("\nCondition on arrays\n");
var arr = [1, 2, 3, 4, 5, 10, 15, 20];
var toFind = 5;
var index = arr.indexOf(toFind);
console.log(index !== -1);
toFind = 8;
index = arr.indexOf(toFind);
console.log(index !== -1);
